**建立資料**

In [11]:
import tensorflow as tf

X = tf.constant([[1.0,2.0,3.0],[4.0,5.0,6.0]])
Y = tf.constant([[10.0],[20.0]])

**建模型**

In [16]:
class Linear(tf.keras.Model):
  def __init__(self):
    super().__init__()
    self.dense = tf.keras.layers.Dense(
        units=10000,
        activation=None,
        kernel_initializer=tf.zeros_initializer(),
        bias_initializer=tf.zeros_initializer()
    )

  def call(self,input):
    output = self.dense(input)
    return output

**運行**

In [17]:
model = Linear()
optimizer = tf.keras.optimizers.SGD(learning_rate=0.01)

for i in range(100):
  with tf.GradientTape() as tape:
    y_pred = model(X)
    loss = tf.reduce_sum(tf.square(y_pred - Y))
  grads = tape.gradient(loss,model.variables)
  optimizer.apply_gradients(grads_and_vars=zip(grads,model.variables))

  print(model.variables)

[<tf.Variable 'linear_5/dense_5/kernel:0' shape=(3, 10000) dtype=float32, numpy=
array([[1.8      , 1.8      , 1.8      , ..., 1.8      , 1.8      ,
        1.8      ],
       [2.3999999, 2.3999999, 2.3999999, ..., 2.3999999, 2.3999999,
        2.3999999],
       [3.       , 3.       , 3.       , ..., 3.       , 3.       ,
        3.       ]], dtype=float32)>, <tf.Variable 'linear_5/dense_5/bias:0' shape=(10000,) dtype=float32, numpy=
array([0.59999996, 0.59999996, 0.59999996, ..., 0.59999996, 0.59999996,
       0.59999996], dtype=float32)>]
[<tf.Variable 'linear_5/dense_5/kernel:0' shape=(3, 10000) dtype=float32, numpy=
array([[0.25200045, 0.25200045, 0.25200045, ..., 0.25200045, 0.25200045,
        0.25200045],
       [0.37200022, 0.37200022, 0.37200022, ..., 0.37200022, 0.37200022,
        0.37200022],
       [0.49200058, 0.49200058, 0.49200058, ..., 0.49200058, 0.49200058,
        0.49200058]], dtype=float32)>, <tf.Variable 'linear_5/dense_5/bias:0' shape=(10000,) dtype=float32, nu